{
  try {
    close();
  }
 catch (  NamingException e) {
  }
}
