{
  try {
    return method.invoke(this,args);
  }
 catch (  InvocationTargetException e) {
    throw e.getCause();
  }
}
