{
  try {
    prev.undeploy(deploymentUnitContext);
  }
 catch (  Throwable t) {
    log.errorf(t,"Deployment unit processor %s unexpectedly threw an exception during undeploy of %s",prev,deploymentUnitContext);
  }
}
