{
  try {
    uba.begin();
    client1.saveData();
    client2.saveData(APPLICATION_EXCEPTION);
    Assert.fail("Exception should have been thrown by now");
  }
 catch (  TestApplicationException e) {
  }
 finally {
    client3.saveData();
    uba.cancel();
  }
  assertEventLogClient1(CANCEL);
  assertEventLogClient2(CANCEL);
  assertEventLogClient3(CANCEL);
}
