{
  AsyncBean bean=lookup(AsyncBean.class);
  Future<String> future=bean.asyncMethodWithException(true);
  try {
    future.get();
    Assert.fail("ExecutionException was expected");
  }
 catch (  ExecutionException ee) {
    Assert.assertNotNull(ee.getCause());
  }
catch (  Exception e) {
    Assert.fail("ExecutionException was expected and not " + e.getClass());
  }
}
