{
  assertNotNull(fooInstance);
  FooAroundInvokeInterceptor.reset();
  try {
    Foo foo=fooInstance.get();
    foo.doSomething();
    fail("Exception in AroundInvoke interceptor method was suppressed.");
  }
 catch (  Exception e) {
  }
  assertTrue(FooAroundInvokeInterceptor.isAroundInvokeCalled());
}
