{
  try {
    uba.begin();
    client1.saveData();
    client2.saveData(SYSTEM_EXCEPTION_ON_COMPLETE);
    client3.saveData();
    uba.close();
    Assert.fail("Exception should have been thrown by now");
  }
 catch (  com.arjuna.wst.TransactionRolledBackException trbe) {
  }
 finally {
    assertEventLogClient1(COMPLETE,CONFIRM_COMPLETED,COMPENSATE);
    assertEventLogClient2(COMPLETE,CANCEL);
    assertEventLogClient3(CANCEL);
  }
}
