{
  try {
    singletonBean.start();
    Assert.fail("Expected an EJBException");
  }
 catch (  EJBException expected) {
    final Throwable cause=expected.getCause();
    Assert.assertTrue("Expected exception cause to be an java.lang.IllegalStateException, but it was a " + cause,cause instanceof IllegalStateException);
  }
}
