{
  try {
    ut.begin();
    client1.invoke();
    client2.invoke(APPLICATION_EXCEPTION);
    Assert.fail("Exception should have been thrown by now");
  }
 catch (  TestApplicationException e) {
  }
 finally {
    client3.invoke();
    ut.commit();
  }
  assertEventLogClient1(BEFORE_PREPARE,PREPARE,COMMIT,VOLATILE_COMMIT);
  assertEventLogClient2(BEFORE_PREPARE,PREPARE,COMMIT,VOLATILE_COMMIT);
  assertEventLogClient3(BEFORE_PREPARE,PREPARE,COMMIT,VOLATILE_COMMIT);
}
