{
  try {
    prev.undeploy(deploymentUnit);
  }
 catch (  Throwable t) {
    log.errorf(t,"Deployment unit processor %s unexpectedly threw an exception during undeploy phase %s of %s",prev,phase,deploymentUnit);
  }
}
